### ISSUE TITLE
xuegao-issues-阮一峰的网络日志，https://www.ruanyifeng.com/blog/archives.html

### ISSUE THREAD

**Issue by WarriorFromLongAgo** [WarriorFromLongAgo/xuegao_public_blog#5]
科技爱好者周刊（第 230 期）：电子产品的用电量

浙江大学附属第一医院的自动发药机，医生一开完处方，机器手就自动开始抓药，然后通过管道"投送"到药师窗口，等患者取药。（[via](https://www.cn-healthcare.com/articlewm/20221101/wap-content-1459477.html)）

1，缓存 OPTIONS 跨域请求
https://httptoolkit.com/blog/cache-your-cors/
https://httptoolkit.com/ 拦截http请求

浏览器的 CORS 缓存
Access-Control-Max-Age: 86400，这是以秒为单位的缓存时间。
浏览器对此进行了限制，

适用于 CDN 的 CORS 缓存
Cache-Control: public, max-age=86400
Vary: origin

配置示例
```js
exports.handler = async (event) => {
    const response = {
        statusCode: 200,
        headers: {
            // Keep your existing CORS headers:
            "Access-Control-Allow-Origin": event.headers['origin'],
            // ...

            // And add these:
            "Access-Control-Max-Age": 86400,
            "Cache-Control": "public, max-age=86400",
            "Vary": "origin"
        }
    };

    return response;
};
```

您使用的是[无服务器框架](https://www.serverless.com/)
```yml
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors:
            origin: '*'
            maxAge: 86400
            cacheControl: 'public, max-age=86400'

```

使用 Java Spring 缓存 CORS
默认情况下，Spring 会设置一个 30 分钟的标头，在每个单独的浏览器中添加相对较短的缓存，但不会设置 aheader。Access-Control-Max-AgeCache-Control
```java
@Component
public class AddPreflightCacheControlWebFilter implements WebFilter {
    @Override
    public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
        if (CorsUtils.isPreFlightRequest(exchange.getRequest())) {
            exchange.getResponse()
                .getHeaders()
                .add("Cache-Control", "public, max-age=86400");
        }
        return chain.filter(exchange);
    }
}

```

2，初创公司的快速交付
https://growing-products.paralect.com/a-development-process-startup-founders-should-use-to-ship-features-weirdly-fast

避免功能分支
直接在主分支开发
自动CICD
将功能分解为小的增量更改
每周至少申请一次演示

3，将图片从低分辨率变成高分辨率
https://github.com/upscayl/upscayl

3，类似 GitHub Copilot 
[CodeGeeX](https://keg.cs.tsinghua.edu.cn/codegeex/index_zh.html)
https://keg.cs.tsinghua.edu.cn/codegeex/index_zh.html

4，[Lama Cleaner](https://github.com/Sanster/lama-cleaner)
一个开源的 AI 工具，可以从图片上擦除任何不需要的物体。

5，[sonic](https://github.com/go-sonic/sonic)
Sonic 是一个用Golang开发的博客平台，高效快速.
